ArmyTechTask/Models/CashierIndexVM.cs
using ArmyTechTask.Domain;

namespace ArmyTechTask.Models;

public class CashierIndexVM
{
    public IEnumerable<Cashier> Cashiers { get; set; } = default!;
}

ArmyTechTask/Models/CashierUpsertVM.cs
using ArmyTechTask.Domain;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ArmyTechTask.Models;

public class CashierUpsertVM
{
    public Cashier Cashier { get; set; } = default!;

    public IEnumerable<SelectListItem> BranchSelectList { get; set; } = default!;
}

ArmyTechTask/Models/ErrorViewModel.cs
namespace ArmyTechTask.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ArmyTechTask/Models/InvoiceDetailsEditVM.cs
using ArmyTechTask.Domain;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ArmyTechTask.Models
{
    public class InvoiceDetailsEditVM
    {
        public InvoiceHeader Invoice { get; set; } = default!;

        public IEnumerable<SelectListItem> BranchSelectList { get; set; } = default!;

        public IEnumerable<SelectListItem> CashierSelectList { get; set; } = default!;

    }
}

ArmyTechTask/Models/InvoiceIndexVM.cs
using ArmyTechTask.Domain;

namespace ArmyTechTask.Models;

public class InvoiceIndexVM
{
    public IEnumerable<Invoice> Invoices { get; set; } = default!;
}

ArmyTechTask/Controllers/CashierController.cs
using ArmyTechTask.Domain.Repositories;
using ArmyTechTask.Models;
using Microsoft.AspNetCore.Mvc;

namespace ArmyTechTask.Controllers;

public class CashierController : Controller
{
    private readonly IUnitOfWork _unit;

    public CashierController(IUnitOfWork unit)
    {
        _unit = unit ?? throw new ArgumentNullException(nameof(unit));
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        CashierIndexVM viewModel = new()
        {
            Cashiers = await _unit.Cashiers.GetAllCashiersWithBranch()
        };

        return View(viewModel);
    }

    [HttpGet]
    public async Task<IActionResult> Upsert(long? id)
    {
        CashierUpsertVM viewModel = new()
        {
            BranchSelectList = _unit.Cashiers.GetAllBranchesDropdownList()
        };

        if (id is null)
        {
            // Create
            viewModel.Cashier = new();
        }
        else
        {
            // Update
            viewModel.Cashier = await _unit.Cashiers.GetCashierByIdAsync(id.Value);

            if (viewModel.Cashier is null)
                return NotFound();
        }

        return View(viewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Upsert(CashierUpsertVM viewModel)
    {
        if (viewModel.Cashier.Id == 0)
        {
            await _unit.Cashiers.AddAsync(viewModel.Cashier);
        }
        else
        {
            _unit.Cashiers.Update(viewModel.Cashier);
        }

        await _unit.SaveAsync();
        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteCashier(long id)
    {
        var cashier = await _unit.Cashiers.GetCashierByIdAsync(id);

        if (cashier is null)
            return NotFound();

        _unit.Cashiers.Delete(cashier);
        await _unit.SaveAsync();

        return RedirectToAction(nameof(Index));
    }
}

ArmyTechTask/Controllers/HomeController.cs
using ArmyTechTask.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ArmyTechTask.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

ArmyTechTask/Controllers/InvoiceController.cs
using ArmyTechTask.Domain.Repositories;
using ArmyTechTask.Models;
using Microsoft.AspNetCore.Mvc;

namespace ArmyTechTask.Controllers;

public class InvoiceController : Controller
{
    private readonly IUnitOfWork _unit;

    public InvoiceController(IUnitOfWork unit)
    {
        _unit = unit ?? throw new ArgumentNullException(nameof(unit));
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        InvoiceIndexVM viewModel = new()
        {
            Invoices = await _unit.Invoices.GetAllAsync()
        };

        return View(viewModel);
    }

    [HttpGet]
    public async Task<IActionResult> DetailsEdit(long id)
    {
        InvoiceDetailsEditVM viewModel = new()
        {
            Invoice = await _unit.InvoiceHeaders.GetInvoiceHeadersWithRelations(id),
            BranchSelectList = _unit.Invoices.GetAllBranchesDropdownList(),
            CashierSelectList = _unit.Invoices.GetAllCashiersDropdownList()
        };

        return View(viewModel);
    }

    [HttpPost]
    public async Task<IActionResult> DetailsEdit(InvoiceDetailsEditVM viewModel)
    {
        _unit.InvoiceHeaders.Update(viewModel.Invoice);
        await _unit.SaveAsync();

        return RedirectToAction(nameof(Index));
    }
}

ArmyTechTask/Views/Cashier/Index.cshtml
@model CashierIndexVM
@{
    ViewData["Title"] = "Index";
}

<div class="p-1">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Cashiers</h2>
        </div>
        <div class="col-6 text-end">
            <a class="btn btn-primary" asp-action="Upsert">
                <i class="bi bi-plus-circle"></i> &nbsp; Create New Cashier
            </a>
        </div>
    </div>
    <br />
    <table class="table table-bordered table-striped text-center" style="width:100%">
        <thead>
            <tr>
                <th>
                    ID
                </th>
                <th>
                    Cashier Name
                </th>
                <th>
                    Branch Name
                </th>
                <th>
                    Branch ID
                </th>
                <th>
                    Actions
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var cashier in Model.Cashiers)
            {
                <tr>
                    <td width="10%">
                        @cashier.Id
                    </td>
                    <td width="30%">
                        @cashier.CashierName
                    </td>
                    <td width="30%">
                        @cashier.Branch.BranchName
                    </td>
                    <td width="10%">
                        @cashier.BranchId
                    </td>
                    <td>
                        <div class="w-100 btn-group" role="group">
                            <a asp-action="Upsert" asp-route-id="@cashier.Id" class="btn btn-primary">
                                <i class="bi bi-pencil-square"></i> Edit
                            </a>
                            <button class="btn btn-danger" data-bs-id="@cashier.Id" data-bs-toggle="modal" data-bs-target="#deleteModal">
                                <i class="bi bi-trash-fill"></i> Delete
                            </button>
                        </div>
                    </td>
                </tr>
            }
        </tbody>

    </table>
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Confirm Deleting Cashier</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p id="modalBodyContent"></p>
                </div>
                <div class="modal-footer">
                    <form id="modalForm" method="post" asp-action="Delete">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-danger">Confirm Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>

@section Scripts {
    <script>
        const exampleModal = document.getElementById('deleteModal');
        const modalForm = document.getElementById('modalForm');

        exampleModal.addEventListener('show.bs.modal', event => {
            const button = event.relatedTarget;
            const data = button.getAttribute('data-bs-id');
            modalForm.setAttribute('action', '/Cashier/DeleteCashier/' + data);

            const modalBodyContent = exampleModal.querySelector('#modalBodyContent');
            modalBodyContent.innerHTML = `Are you sure to delete Cashier of ID ${data}? This action cannot be revoked.`;
        });
    </script>
}

ArmyTechTask/Views/Cashier/Upsert.cshtml
@model CashierUpsertVM
@{
    ViewData["Title"] = "Add Cashier";
}

<form method="post" asp-action="Upsert">
    @if (Model.Cashier.Id != 0)
    {
        ViewData["Title"] = "Edit Cashier";
        <input asp-for="Cashier.Id" hidden />
    }

    <div class="border p-3 bg-white">
        <div class="form-group row">
            <h2 class="text-info pl-3">@ViewData["Title"]</h2>
        </div>
        <div class="col-8">
            <div class="form-group row py-2">
                <div class="col-4">
                    <label asp-for="Cashier.CashierName"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Cashier.CashierName" class="form-control" />
                    <span asp-validation-for="Cashier.CashierName" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row py-2">
                <div class="col-4">
                    <label asp-for="Cashier.BranchId"></label>
                </div>
                <div class="col-8">
                    <select asp-for="Cashier.BranchId" asp-items="@Model.BranchSelectList" class="form-select">
                        <option disabled selected>--Select Branch--</option>
                    </select>
                    <span asp-validation-for="Cashier.BranchId" class="text-danger"></span>
                </div>

            </div>
            <div class="form-group row py-2">
                <div class="col-8 offset-4 row">
                    <div class="col">
                        @if (Model.Cashier.Id != 0)
                        {
                            // Update
                            <input type="submit" class="btn btn-info w-100" value="Update" />
                        }
                        else
                        {
                            // Create
                            <input type="submit" class="btn btn-primary w-100" value="Create" />
                        }

                    </div>
                    <div class="col">
                        <a asp-action="Index" class="btn btn-secondary w-100"><i class="bi bi-box-arrow-left"></i> Back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

</form>

ArmyTechTask/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Task Demo!</h1>
    <p>Invoice Db View can be viewed <a asp-controller="Invoice" asp-action="Index">from here</a>.</p>
</div>

ArmyTechTask/Views/Invoice/DetailsEdit.cshtml
@model InvoiceDetailsEditVM
@{
    ViewData["Title"] = "Edit Invoice";

    double sum = 0;
}

<form method="post" asp-action="DetailsEdit">
    <input asp-for="Invoice.Id" hidden />

    <div class="border p-3 bg-white">
        <div class="form-group row">
            <h2 class="text-info pl-3">Edit Invoice Header</h2>
        </div>
        <div class="w-100">
            <div class="form-group row py-2">
                <div class="col-4">
                    <label asp-for="Invoice.CustomerName"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Invoice.CustomerName" class="form-control" />
                    <span asp-validation-for="Invoice.CustomerName" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row py-2">
                <div class="col-4">
                    <label asp-for="Invoice.Invoicedate"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Invoice.Invoicedate" class="form-control" />
                    <span asp-validation-for="Invoice.Invoicedate" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row py-2">
                <div class="col-4">
                    <label asp-for="Invoice.CashierId"></label>
                </div>
                <div class="col-8">
                    <select asp-for="Invoice.CashierId" asp-items="@Model.CashierSelectList" class="form-select">
                        <option disabled selected>--Select Cashier--</option>
                    </select>
                    <span asp-validation-for="Invoice.CashierId" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row py-2">
                <div class="col-4">
                    <label asp-for="Invoice.BranchId"></label>
                </div>
                <div class="col-8">
                    <select asp-for="Invoice.BranchId" asp-items="@Model.BranchSelectList" class="form-select">
                        <option disabled selected>--Select Branch--</option>
                    </select>
                    <span asp-validation-for="Invoice.BranchId" class="text-danger"></span>
                </div>
            </div>
            <hr />
            <div class="row pt-4">
                <div class="col-6">
                    <h2 class="text-primary">Invoice Items</h2>
                </div>
                <div class="col-6 text-end">
                    <button type="button" class="btn btn-primary"
                            data-bs-name=""
                            data-bs-count="0"
                            data-bs-price="0"
                            data-bs-toggle="modal" data-bs-target="#upsertModal">
                        <i class="bi bi-plus-circle"></i> &nbsp; Create New Invoice Item
                    </button>
                    <div class="modal fade" id="upsertModal" tabindex="-1" aria-labelledby="upsertModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="upsertModalLabel">Insert / Edit Invoice Item</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body text-start">
                                    <div class="mb-3">
                                        <label for="itemName" class="form-label">Item Name</label>
                                        <input type="text" class="form-control" id="itemName" placeholder="Enter item's name">
                                    </div>
                                    <div class="mb-3">
                                        <label for="itemCount" class="form-label">Item Count</label>
                                        <input type="number" class="form-control" id="itemCount" placeholder="Enter item's count">
                                    </div>
                                    <label for="itemPrice" class="form-label">Item Price</label>
                                    <div class="input-group mb-3">
                                        <input type="number" class="form-control" placeholder="Enter item's price" aria-label="Enter item's price" aria-describedby="basic-addon2">
                                        <span class="input-group-text" id="basic-addon2">L.E.</span>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                    <button type="button" class="btn btn-success">Save</button>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            <br />
            <table class="table table-bordered table-striped text-center" style="width:100%">
                <thead>
                    <tr>
                        <th>
                            ID
                        </th>
                        <th>
                            Item Name
                        </th>
                        <th>
                            Item Count
                        </th>
                        <th>
                            Item Price
                        </th>
                        <th>
                            Actions
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Invoice.InvoiceDetails)
                    {
                        <tr>
                            <td width="10%">
                                @item.Id
                            </td>
                            <td width="30%">
                                @item.ItemName
                            </td>
                            <td width="20%">
                                @item.ItemCount
                            </td>
                            <td width="20%">
                                @(item.ItemPrice) L.E.
                                <p hidden>@(sum += item.ItemPrice)</p>
                            </td>
                            <td>
                                <div class="w-100 btn-group" role="group">
                                    <button type="button" class="btn btn-primary"
                                        data-bs-id="@item.Id"
                                        data-bs-name="@item.ItemName"
                                        data-bs-count="@item.ItemCount"
                                        data-bs-price="@item.ItemPrice"
                                        data-bs-toggle="modal" data-bs-target="#upsertModal">
                                        <i class="bi bi-pencil-square"></i> Edit
                                    </button>
                                    <button type="button" class="btn btn-danger" 
                                        data-bs-id="@item.Id" data-bs-toggle="modal" data-bs-target="#deleteModal">
                                        <i class="bi bi-trash-fill"></i> Delete
                                    </button>
                                </div>
                            </td>
                        </tr>
                    }

                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>@(sum) L.E.</td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
            <!-- Delete Modal-->
            <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="deleteModalLabel">Invoice Item Removal</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <p id="modalBodyContent"></p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-danger">Remove</button>
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-group row py-2">
                <div class="col-4 offset-8 row">
                    <div class="col">
                        <input type="submit" class="btn btn-info w-100" value="Update" />
                    </div>
                    <div class="col">
                        <a asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-box-arrow-left"></i> Back
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

</form>

@section Scripts {
    <script>
        // Upsert Modal
        const exampleModal = document.getElementById('upsertModal');

        exampleModal.addEventListener('show.bs.modal', event => {
            const button = event.relatedTarget;

            var dataId = button.getAttribute('data-bs-id');
            var dataName = button.getAttribute('data-bs-name');
            var dataCount = button.getAttribute('data-bs-count');
            var dataPrice = button.getAttribute('data-bs-price');

            var modalTextboxes = exampleModal.getElementsByClassName('form-control');

            modalTextboxes[0].setAttribute('value', dataName);
            modalTextboxes[1].setAttribute('value', dataCount);
            modalTextboxes[2].setAttribute('value', dataPrice);
        });

        // Delete Modal
        const deleteModal = document.getElementById('deleteModal');
        const modalForm = document.getElementById('modalForm');

        deleteModal.addEventListener('show.bs.modal', event => {
            const button = event.relatedTarget;
            const data = button.getAttribute('data-bs-id');
            //modalForm.setAttribute('action', '/Cashier/DeleteCashier/' + data);

            const modalBodyContent = deleteModal.querySelector('#modalBodyContent');
            modalBodyContent.innerHTML = `Are you sure to delete Invoice Item of ID ${data}? This action cannot be revoked.`;
        });
    </script>
}

ArmyTechTask/Views/Invoice/Index.cshtml
@model InvoiceIndexVM
@{
    ViewData["Title"] = "Index";
}

<div class="p-1">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Invoices (From Db View)</h2>
        </div>
    </div>
    <br />
    <table class="table table-bordered table-striped text-center" style="width:100%">
        <thead>
            <tr>
                <th>
                    ID
                </th>
                <th>
                    Customer Name
                </th>
                <th>
                    Invoice Date
                </th>
                <th>
                    Cashier ID
                </th>
                <th>
                    Branch ID
                </th>
                <th>
                    Invoice Total
                </th>
                <th>
                    Actions
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var invoice in Model.Invoices)
            {
                <tr>
                    <td width="10%">
                        @invoice.Id
                    </td>
                    <td width="20%">
                        @invoice.CustomerName
                    </td>
                    <td width="20%">
                        @invoice.Invoicedate
                    </td>
                    <td width="10%">
                        @invoice.CashierId
                    </td>
                    <td width="10%">
                        @invoice.BranchId
                    </td>
                    <td width="10%">
                        @invoice.InvoiceTotal
                    </td>
                    <td>
                        <div class="w-100 btn-group" role="group">
                            <a asp-action="DetailsEdit" asp-route-id="@invoice.Id" class="btn btn-primary">
                                <i class="bi bi-pencil-square"></i> Details
                            </a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

ArmyTechTask/Views/Shared/_Layout.cshtml
@{
    string IsViewActive(string controllerActionName) 
    => $"{ViewContext.RouteData.Values["controller"]!}-{ViewContext.RouteData.Values["action"]!}" == controllerActionName 
        ? "active" : string.Empty;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ArmyTech Task</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ArmyTechTask.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">ArmyTech Task</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link @IsViewActive("Home-Index")" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link @IsViewActive("Home-Privacy")" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link @IsViewActive("Cashier-Index")" asp-controller="Cashier" asp-action="Index">Cashiers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link @IsViewActive("Invoice-Index")" asp-controller="Invoice" asp-action="Index">Invoices</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ArmyTech Task
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>